version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - keycloak-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    restart: unless-stopped
    environment:
     - KC_DB=postgres
     - KC_DB_USERNAME=postgres
     - KC_DB_PASSWORD=postgres
     - KC_DB_SCHEMA=public
     - KC_DB_URL_DATABASE=keycloak
     - KC_DB_URL_HOST=keycloak-db 
     - KC_DB_URL_PORT=5432
     - KC_HOSTNAME_STRICT=false
     - KC_HTTP_ENABLED="true"
     - KC_HTTP_PORT=8080
     - KC_METRICS_ENABLED=true
     - KC_PROXY=edge
     - KEYCLOAK_ADMIN=Admin
     - KEYCLOAK_ADMIN_PASSWORD=Admin
     - PROXY_ADDRESS_FORWARDING=true
     - KC_FEATURES="authorization, token-exchange"
        # - authorization
        # - token-exchange
        # - docker
        # - impersonation
        # - scripts
        # - upload-scripts
        # - web-authn
        # - client-policies
        # - dynamic-scopes
    entrypoint: /opt/keycloak/bin/kc.sh start
    ports:
      - 8080:8080
      # - 8443:8443
    networks:
      - keycloak-network
    depends_on:
      - db

networks:
  keycloak-network:
    driver: bridge